# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfvarenv < Formula
  desc ""
  homepage ""
  version "0.0.3"

  on_macos do
    on_intel do
      url "https://github.com/marcy326/tfvarenv/releases/download/v0.0.3/tfvarenv_v0.0.3_darwin_amd64.tar.gz"
      sha256 "21c3eb09ac277701971476c90abef52e5a7ef58135c1b82846b86280395bdf9b"

      def install
        bin.install "tfvarenv"
      end
    end
    on_arm do
      url "https://github.com/marcy326/tfvarenv/releases/download/v0.0.3/tfvarenv_v0.0.3_darwin_arm64.tar.gz"
      sha256 "9c0ed5fbe480c889fe5ef6cf9aab47baeca039d26f8d3f556059f4a72e222a8b"

      def install
        bin.install "tfvarenv"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marcy326/tfvarenv/releases/download/v0.0.3/tfvarenv_v0.0.3_linux_amd64.tar.gz"
        sha256 "85e22a2ed3180d37ee55ce8499bf28d1c70d279a7c037a9ffe550012ac52281f"

        def install
          bin.install "tfvarenv"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marcy326/tfvarenv/releases/download/v0.0.3/tfvarenv_v0.0.3_linux_arm64.tar.gz"
        sha256 "c2c16b73e8927c16d25a470a4915727a0dac50efdad55a0c224f56346d39cb6a"

        def install
          bin.install "tfvarenv"
        end
      end
    end
  end
end
