# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfvarenv < Formula
  desc ""
  homepage ""
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marcy326/tfvarenv/releases/download/v0.3.0/tfvarenv_v0.3.0_darwin_amd64.tar.gz"
      sha256 "c4a264f3ae81fe5fb14f27d623f77d716179b0560118a8979d90d8ba6a19b495"

      def install
        bin.install "tfvarenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marcy326/tfvarenv/releases/download/v0.3.0/tfvarenv_v0.3.0_darwin_arm64.tar.gz"
      sha256 "9a52e78e3e8e71601e4739c6c1e488725a6dce2d251ab06335515bcd95f3f497"

      def install
        bin.install "tfvarenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marcy326/tfvarenv/releases/download/v0.3.0/tfvarenv_v0.3.0_linux_amd64.tar.gz"
        sha256 "ca56648031178b441484079edba32b393214b3d04b48965076cef11704f323a6"

        def install
          bin.install "tfvarenv"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marcy326/tfvarenv/releases/download/v0.3.0/tfvarenv_v0.3.0_linux_arm64.tar.gz"
        sha256 "9c3f26909ffbc4a4bcc3e6e3a70335ead2484e39190c06b34682797b35047638"

        def install
          bin.install "tfvarenv"
        end
      end
    end
  end
end
