# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfvarenv < Formula
  desc ""
  homepage ""
  version "0.3.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marcy326/tfvarenv/releases/download/v0.3.3/tfvarenv_v0.3.3_darwin_amd64.tar.gz"
      sha256 "cd1498007bc49f00c79da59b2e9a38c8442ed4ca2ed1fb155108cdbba5145ca5"

      def install
        bin.install "tfvarenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marcy326/tfvarenv/releases/download/v0.3.3/tfvarenv_v0.3.3_darwin_arm64.tar.gz"
      sha256 "7e6488cccc71e3a1a57bf9460196e62c1db6ed5d4d54e33c3b1bc8fc5ecd3dc4"

      def install
        bin.install "tfvarenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marcy326/tfvarenv/releases/download/v0.3.3/tfvarenv_v0.3.3_linux_amd64.tar.gz"
        sha256 "dfcd6d7bbf3bb9b42664e0b2af8ea599e3569e524534baae92ed8d47f1d18504"

        def install
          bin.install "tfvarenv"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marcy326/tfvarenv/releases/download/v0.3.3/tfvarenv_v0.3.3_linux_arm64.tar.gz"
        sha256 "406ca0c4daf58ada82d14ed3c81c07782486f91e75f73d7eef54b3f1bf818d29"

        def install
          bin.install "tfvarenv"
        end
      end
    end
  end
end
