# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sonyport < Formula
  desc "Unofficial macOS CLI for importing photos and videos from mounted Sony cameras"
  homepage "https://github.com/marcy326/sonyport"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/marcy326/sonyport/releases/download/v0.1.0/sonyport_0.1.0_darwin_amd64.zip"
    sha256 "1fce48df6c9dd09dc0a206551323fa74f0e0365a4aeea5cf1ab9abd4d1c2e425"

    define_method(:install) do
      bin.install "sonyport"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/marcy326/sonyport/releases/download/v0.1.0/sonyport_0.1.0_darwin_arm64.zip"
    sha256 "824faaf79f8b31a4c413645fc4ae987b20270ae4ddd997b557d8dd47ef3cbc57"

    define_method(:install) do
      bin.install "sonyport"
    end
  end

  test do
    system "#{bin}/sonyport", "--help"
  end
end
