# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfvarenv < Formula
  desc ""
  homepage ""
  version "0.3.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marcy326/tfvarenv/releases/download/v0.3.5/tfvarenv_v0.3.5_darwin_amd64.tar.gz"
      sha256 "011213db8faa9ba66d3204783738fd9a1d23e64bb46e7a203da9e5dbb3645956"

      define_method(:install) do
        bin.install "tfvarenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marcy326/tfvarenv/releases/download/v0.3.5/tfvarenv_v0.3.5_darwin_arm64.tar.gz"
      sha256 "41d6a0827d3e96f3ce7ad87b96993b5c7617354a8c67f915e8212c3a7e2b2ead"

      define_method(:install) do
        bin.install "tfvarenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/marcy326/tfvarenv/releases/download/v0.3.5/tfvarenv_v0.3.5_linux_amd64.tar.gz"
      sha256 "68d3edfb070190d9317ef8689055f541f0f9fc67a3014718ed857651d409c94d"
      define_method(:install) do
        bin.install "tfvarenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marcy326/tfvarenv/releases/download/v0.3.5/tfvarenv_v0.3.5_linux_arm64.tar.gz"
      sha256 "6bf8b3b43275dc52756d59e10a82ad4967e9d084f20d2c3eff7240862190fdcd"
      define_method(:install) do
        bin.install "tfvarenv"
      end
    end
  end
end
